# Generated by Django 4.1.2 on 2022-11-14 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='Answers',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
