# Generated by Django 4.1.2 on 2022-12-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_alter_questions_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
